using NF.NotaFiscal.DataContract;

namespace NF.NotaFiscal
{
    //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.ginfes.com.br/servico_consultar_lote_rps_envio_v03.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(
        Namespace = "http://www.ginfes.com.br/servico_consultar_lote_rps_envio_v03.xsd", IsNullable = false)]
    public partial class ConsultarLoteRpsEnvio
    {
        private tcIdentificacaoPrestador prestadorField;

        private string protocoloField;

        private SignatureType signatureField;

        /// <remarks/>
        public tcIdentificacaoPrestador Prestador
        {
            get { return this.prestadorField; }
            set { this.prestadorField = value; }
        }

        /// <remarks/>
        public string Protocolo
        {
            get { return this.protocoloField; }
            set { this.protocoloField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
        public SignatureType Signature
        {
            get { return this.signatureField; }
            set { this.signatureField = value; }
        }
    }
}