namespace NF.NotaFiscal.DataContract
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://www.ginfes.com.br/servico_consultar_nfse_rps_envio_v03.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(
        Namespace = "http://www.ginfes.com.br/servico_consultar_nfse_rps_envio_v03.xsd", IsNullable = false)]
    public partial class ConsultarNfseRpsEnvio
    {
        private tcIdentificacaoRps identificacaoRpsField;

        private tcIdentificacaoPrestador prestadorField;

        /// <remarks/>
        public tcIdentificacaoRps IdentificacaoRps
        {
            get { return this.identificacaoRpsField; }
            set { this.identificacaoRpsField = value; }
        }

        /// <remarks/>
        public tcIdentificacaoPrestador Prestador
        {
            get { return this.prestadorField; }
            set { this.prestadorField = value; }
        }
    }
}